import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import ProjectContainer from '../components/ProjectContainer'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Profile from '../components/Profile'

const listProject = [
  {
    src: '/images/project/project-1.png',
    title: 'Project 1',
    description: 'Description Project 1',
    slug: 'project-1'
  },
  {
    src: '/images/project/project-2.png',
    title: 'Project 2',
    description: 'Description Project 2',
    slug: 'project-2'
  },
  {
    src: '/images/project/project-3.png',
    title: 'Project 3',
    description: 'Description Project 3',
    slug: 'project-3'
  },
  {
    src: '/images/project/project-4.png',
    title: 'Project 4',
    description: 'Description Project 4',
    slug: 'project-4'
  },
  {
    src: '/images/project/project-5.png',
    title: 'Project 5',
    description: 'Description Project 5',
    slug: 'project-5'
  },
  {
    src: '/images/project/project-6.png',
    title: 'Project 6',
    description: 'Description Project 6',
    slug: 'project-6'
  },
]

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="xl:container mt-8">

        <Profile />

        {/* List Project */}
        <ProjectContainer list={listProject} />
        {/* End List Project */}

      </main>

      <Footer />

    </div>
  )
}

export default Home
